### ISSUE TITLE
Request to support podman

### ISSUE THREAD

**Issue by LinuxSuRen** [illa-family/illa#25]
I'm working on WSL2. Podman is ready in my environment. I'm wondering if it's possible to support podman. As we know that Docker is not the only container tech, and Podman is very popular too.

**Comment by naj1n** [comment]
Thanks for the feedback. We'll take a discussion between illa family.

**Comment by karminski** [comment]
@LinuxSuRen Hi, We already support manual deployment, and you can modify scripts for WSL2. Please check it out. [deploy-illa-manually](https://github.com/illacloud/deploy-illa-manually). 

Currently, we have no plans to support WSL2 in the illacli.
