### ISSUE TITLE
[BUG] cli部署illa builder 后，注册账户及登录界面会显示网络异常。

### ISSUE THREAD

**Issue by whthend** [illa-family/illa#34]
**Describe the bug**
在使用cli部署illa builder 后，注册账户及登录界面会显示网络异常。

**Desktop (please complete the following information):**
 - OS: windows
 - Browser: edge

**Comment by naj1n** [comment]
@whthend please provide some docker logs for this bug. Thx.

**Comment by whthend** [comment]
防火墙端口未开启
