### ISSUE TITLE
[BUG] Create a new program,error in console and page

### ISSUE THREAD

**Issue by HOLYYUN** [illa-family/illa#50]
![image](https://user-images.githubusercontent.com/22185629/203461080-c166fd3b-118f-4d94-8aa5-70a22194977d.png)

**Comment by HOLYYUN** [comment]
New Error,“http://%3Cserver_address%3E:9999/api/v1/auth/signin”，I think it should be localhost。
 ![image](https://user-images.githubusercontent.com/22185629/203461769-26309e40-d5f1-43aa-a265-ea22e0151508.png)

**Comment by HOLYYUN** [comment]
so what is the correct serve-addr arg I should input? “ illa deploy --self --port=10000 --server-addr=locahost” or “ illa deploy --self --port=10000 --server-addr=<SERVER_ADDRESS>”

**Comment by naj1n** [comment]
If u want to use illa-builder in ur machine, u do not need to input the arg `--server-addr`. The default value of this arg is `localhost`. It's required when u want to deploy illa-builder in ur cloud server and visit it on another computer.

**Comment by naj1n** [comment]
We'll close this issue according to [our issue rules](https://github.com/illacloud/illa/blob/main/ISSUES.md#the-issue-life-cycle).
