### ISSUE TITLE
[BUG] self-host does not work

### ISSUE THREAD

**Issue by egidijus** [illa-family/illa#61]
**Describe the bug**
docker-compose `ILLA_DEPLOY_MODE=SELF_HOST` env vars do nothing.
the docs mention `ILLA_DEPLOY_MODE=self-host` and `ILLA_DEPLOY_MODE='self-host'` both of which seem to be incorrect unless the application does case and dash to underscore transformation.

**To Reproduce**
1. Go to [link](https://github.com/illacloud/deploy-illa-manually/tree/main/docker-compose)
2. follow instructions.
3. ui still asks you to enter email address to login.

**Expected behavior**
login with self_hosted mode

**Desktop (please complete the following information):**
 - OS: linux
 - Browser firefox
 - Version 109

**Additional context**

**Comment by karminski** [comment]
@egidijus Hi, the docker compose and k8s deployment are only for cloud mode. For self-host mode (default root user included, do not need signup), please try the docker all-in-one image: https://github.com/illacloud/deploy-illa-manually/tree/main/docker

**Comment by egidijus** [comment]
@karminski in that case, the docs are incorrect, please fix:
https://github.com/illacloud/deploy-illa-manually/tree/main/docker-compose#run-official-slim-image

```
And Login with default username root and password password.
```

https://github.com/illacloud/deploy-illa-manually/blob/f9fb2f98f8d8d05313d86044a8f65e91481e61db/docker-compose/docker-compose.yml#L31

https://github.com/illacloud/deploy-illa-manually/blob/f9fb2f98f8d8d05313d86044a8f65e91481e61db/docker-compose/docker-compose-with-official-images.yml#L31

**Comment by karminski** [comment]
@egidijus indeed, thanks! I already fixed the README.md in it.
