### ISSUE TITLE
self host deploy, api host is 0.0.0.0

### ISSUE THREAD

**Issue by zigo928** [illa-family/illa#64]
http://0.0.0.0:9999/api/v1/auth/signin 登录的时候看请求地址是这个，Mac下部署的

**Comment by zigo928** [comment]
我是一开始使用执行下面命令部署的
`illa deploy --self --port=10000 --server-addr=0.0.0.0`

然后请求登录发现，请求接口的host是0.0.0.0，便改为下面命令重新部署：

`illa deploy --self --port=10000 --server-addr=127.0.0.1`

还是这样，然后执行 `illa remove --self`并删除了image，执行下面命令部署：

`illa deploy --self --port=10000`

发现api host还是0.0.0.0

**Comment by karminski** [comment]
@zigo928 您好, 您是在本机部署的吗? 还是是远程机器或者虚拟机?

如果不是本机部署(即IP地址不是127.0.0.1), 需要指定--server-addr=为正确的且您本机可以访问的IP地址. 

另外, 第二次指定-server-addr=127.0.0.1的时候应该已经成功了, 建议您尝试清空浏览器缓存再尝试一下. 因为没指定为0.0.0.0还是0.0.0.0很像缓存问题. 源代码中是没有这个地址的.

**Comment by zigo928** [comment]
嗯，应该是缓存的问题，可以正常使用了
