### ISSUE TITLE
[BUG] error: unexpected argument '--server-addr' found

### ISSUE THREAD

**Issue by jaksonlin** [illa-family/illa#76]
**Describe the bug**
according to page : https://www.illacloud.com/zh-CN/docs/illa-cli

user can self-deploy illa using command:

illa deploy --self --port=10000 --server-addr=<SERVER_ADDRESS> --mount=<MOUNT_PATH>

**To Reproduce**
1. ./illa deploy --self --port=10000 --server-addr=192.168.89.129
```
root@ubuntu:/home/ubuntu/illa-x86_64-linux# ./illa deploy --self --port=10000 --server-addr=192.168.89.129
error: unexpected argument '--server-addr' found

```

**Expected behavior**

illa self-host deploy ok and host on addr 192.168.89.129

**Desktop (please complete the following information):**
 - OS: ubuntu 22.04
 - Version illa 1.2.9

**Comment by naj1n** [comment]
Hello,"--server-addr" is removed, the document has been updated. Now you can directly deploy using `illa deploy --self --port=10000 --mount=<MOUNT_PATH>`.

**Comment by karminski** [comment]
closed due to no response.
