### ISSUE TITLE
[BUG] Failed to start with illa deploy --self --port=10000

### ISSUE THREAD

**Issue by x2x4com** [illa-family/illa#81]
**Describe the bug**
Start with `illa deploy --self --port=10000` success but try to open 10000 failed

```
% curl http://localhost:10000
curl: (56) Recv failure: Connection reset by peer
```

Check the docker log for illa_builder find error
```
[envoy]  [2023-05-26 08:46:15.817][119][critical][main] [source/server/server.cc:113] error initializing configuration '/opt/illa/envoy/illa-unit-ingress.yaml': cannot bind '0.0.0.0:80': Permission denied
[envoy]  [2023-05-26 08:46:15.817][119][info][main] [source/server/server.cc:815] exiting
[envoy]  cannot bind '0.0.0.0:80': Permission denied
```

try to use local docker command line to start, also failed

```
docker run --rm -d --name illa_builder -e 'ILLA_SERVER_MODE=release' -e 'ILLA_DEPLOY_MODE=self-host' -e 'POSTGRES_PASSWORD=123456' -e 'ENVOY_UID=0' -e 'ENVOY_GID=0' -p 10000:80 --privileged docker.io/illasoft/illa-builder:latest
```

Docker images Id: b1734e2f3841

**Comment by karminski** [comment]
@x2x4com Hi, for quickly fix, please try run this image as root user.  And could you please more about your runtime environment? Like system version, docker version, current user (in or not in root group)? And put docker logs about this container here. Many thanks.

**Comment by x2x4com** [comment]
I use podman as docker runner, version is 4.4.2(company policy now allow to use Docker-desktop)
Dockerversion: podman 4.4.2
System: MacOS 12.5

try to use --privileged run as root but looks as if not working on podman

**Comment by x2x4com** [comment]
I had tried to run on mac docker-desktop that works fine

**Comment by x2x4com** [comment]
呀，都是国人，那么用中文吧

1. 能不能讲容器内的端口都换成1024以上，这样免于使用特权模式
2. 根据容器化的最佳实践，不要在一个容器内运行多个进程，这样对健康检查也不友好，是否考虑把all in one拆成多个容器并加入Healthcheck(docker stack也可以考虑)

**Comment by karminski** [comment]
@x2x4com 好的，其实情况是这样的，一开始其实是有slim镜像的，每个组件都是单独的镜像。但是需要用户手动配置一下自己机器的host，来确保有一个统一的访问路径。然后..... 发现有好多用户不会配置host.... 导致镜像启动只会访问127.0.0.1 而用户恰好部署的又不在localhost，这样就挂了. 现在的all-in-one实际上是为了体验去做的取舍。

后续我们会提供一个slim镜像供docker compose或者k8s使用。

envoy的问题已经在修复了。预计本周就会换一个非特权接口。我会在修改完成后回复这个issue。

感谢反馈👍

**Comment by karminski** [comment]
@x2x4com hi, 已经修改了 envoy 的监听端口, illa-cli 程序也修改了.

**Comment by karminski** [comment]
issue closed dute to no reply.
