### ISSUE TITLE
[BUG] Website Contact Us Page No Longer Working

### ISSUE THREAD

**Issue by apexclay** [illa-family/illa#89]
**Describe the bug**
The contact us page on the website is no longer working and we cannot contact illacloud though any other means but this github

**To Reproduce**
1. Click on the "Contact Us" button on the website
2. Sign into Discord
3. Complete Captcha for joining the discord
4. Captcha fails "Link Invalid"

**Expected behavior**
Link Valid/a web form to contact illa cloud for business inquiries.

**Additional context**
Would like to discuss self hosted enterprise licensing for larger entities/entities requiring further regulatory compliance and there is no way to contact through the website to do that.

**Comment by apexclay** [comment]
Unknown what was changed. Bug has resolved as of this morning when tested again.

**Comment by dasaf7** [comment]
It doesn't work again, I am not able to contact any support via Discord - "Invite Link Invalid".
